#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RPM-Specfile
version:      1.13
version_from: lib/RPM/Specfile.pm
installdirs:  site
requires:
    File::Copy:                    0
    Getopt::Long:                  0
    URI::Escape:                   0
    File::Basename:                0
    Archive::Tar:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
